# -*- mode: ruby -*-

box = "boxen/ubuntu-24.04"
ram = "65536"
hostname = "wpia-modules"
mac = "00:15:5d:b1:1e:02"
cpus = 8

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.network "public_network", bridge: "External Switch", auto_config: true
  config.vm.provider :hyperv do |hyperv|
    hyperv.mac = mac
    hyperv.vmname = hostname
    hyperv.cpus = cpus
    hyperv.maxmemory = ram
    hyperv.memory = ram
    hyperv.auto_start_action = "StartIfRunning"
    hyperv.auto_stop_action = "Save"
  end
  config.vm.hostname = hostname
  config.vm.synced_folder ".", "/vagrant", disabled: true  
  config.vm.provision :shell, path: "../common/setup.sh",
		                                  env: {"hostname" => hostname}
  config.vm.provision :shell, path: "../common/setup-ssh-keys.sh", run: "always",
                              args: ["richfitz", "weshinsley", "plietar"]
  config.vm.provision :shell, path: "./setup_module.sh"
  config.vm.provision :shell, path: "./setup_easybuild.sh", privileged: false
end
